class ACTION_TYPE {
  static UPDATE_SERVER_ID = "UPDATE_SERVER_ID";
  static UPDATE_TOKEN = "UPDATE_TOKEN";
  static UPDATE_FIRST = "UPDATE_FIRST_OPEN";
  static UPDATE_USER = "UPDATE_USER";
  static UPDATE_USERLOCATION = "UPDATE_USER_LOCATION";
  static UPDATE_ENVI = "UPDATE_ENVI";
  static UPDATE_VISIT_SCHEDULE = "UPDATE_VISITSCHEDULE";
  static UPDATE_SHOW_VISIT_SCHEDULE = "UPDATE_SHOW_VISITSCHEDULE";
  static SET_LOADING = "SET_LOADING";
}

export default ACTION_TYPE;
